version: "3.8"
services:
  mongodb:
    build: ./mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    ports:
      - 27017:$DB_PORT
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./user-service
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:$APP_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - API_SECRET=$API_SECRET
    stdin_open: true
    tty: true
volumes:
  db: