apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    name: mongo-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: mongo-data
